line(12, tram).
line(16, tram).
line(18, tram).
line(27, tram).
line(50, tram).
line(60, tram).
line(61, tram).
line(62, tram).
line(67, tram).
line(68, tram).
line(u1, ubahn).
line(u2, ubahn).
line(u3, ubahn).
line(u4, ubahn).
line(u5, ubahn).
line(u6, ubahn).
line(u7, ubahn).
line(u9, ubahn).
line(u8, ubahn).
line(m2, metrotram).
line(m4, metrotram).
line(m6, metrotram).
line(m8, metrotram).
line(m13, metrotram).
line(s1, sbahn).
line(s2, sbahn).
line(s25, sbahn).
line(s26, sbahn).
line(s3, sbahn).
line(s41, sbahn).
line(s42, sbahn).
line(s45, sbahn).
line(s46, sbahn).
line(s47, sbahn).
line(s5, sbahn).
line(s7, sbahn).
line(s75, sbahn).
line(s8, sbahn).
line(s85, sbahn).
line(s9, sbahn).

unidirectional(s41).
unidirectional(s42).

campus_reachable(borsigwerke).
campus_reachable(tegel).

strike(sbahn, 1, mon).
strike(ubahn, 1, wed).
strike(tram, 1, thu).
strike(ubahn, 3, wed).
strike(tram, 4, tue).
strike(metrotram, 5, thu).
strike(sbahn, 6, mon).
strike(sbahn, 6, tue).
strike(ubahn, 7, sat).
strike(sbahn, 12, wed).

connection(pasedagplatz, berliner_allee_rennbahnstr, 1, 12).
connection(berliner_allee_rennbahnstr, weisser_see, 3, 12).
connection(weisser_see, albertinenstr, 2, 12).
connection(albertinenstr, antonplatz, 1, 12).
connection(antonplatz, behaimstr, 1, 12).
connection(behaimstr, friesickestr, 1, 12).
connection(friesickestr, gustav_adolf_str_langhansstr, 2, 12).
connection(gustav_adolf_str_langhansstr, prenzlauer_allee_ostseestr, 3, 12).
connection(prenzlauer_allee_ostseestr, stahlheimer_str_wisbyer_str, 1, 12).
connection(stahlheimer_str_wisbyer_str, humannplatz, 1, 12).
connection(humannplatz, stargarder_str, 1, 12).
connection(stargarder_str, raumerstr, 1, 12).
connection(raumerstr, eberswalder_str_pappelallee, 2, 12).
connection(eberswalder_str_pappelallee, eberswalder_str, 1, 12).
connection(eberswalder_str, schwedter_str, 2, 12).
connection(schwedter_str, zionskirchplatz, 1, 12).
connection(zionskirchplatz, brunnenstr_invalidenstr, 2, 12).
connection(brunnenstr_invalidenstr, pappelplatz, 1, 12).
connection(pappelplatz, nordbahnhof, 2, 12).
connection(nordbahnhof, naturkundemuseum, 3, 12).
connection(naturkundemuseum, hannoversche_str, 1, 12).
connection(hannoversche_str, oranienburger_tor, 2, 12).
connection(oranienburger_tor, friedrichstr, 3, 12).
connection(friedrichstr, universitaetsstr, 2, 12).
connection(universitaetsstr, am_kupfergraben, 1, 12).
connection(ahrensfelde_stadtgrenze, barnimplatz, 1, 16).
connection(barnimplatz, niemegker_str, 1, 16).
connection(niemegker_str, wuhletalstr, 2, 16).
connection(wuhletalstr, max_herrmann_str, 1, 16).
connection(max_herrmann_str, buergerpark_marzahn, 1, 16).
connection(buergerpark_marzahn, freizeitforum_marzahn, 2, 16).
connection(freizeitforum_marzahn, marzahner_promenade, 2, 16).
connection(marzahner_promenade, marzahn, 1, 16).
connection(marzahn, gewerbepark_georg_knorr, 2, 16).
connection(gewerbepark_georg_knorr, dingelstaedter_str, 1, 16).
connection(dingelstaedter_str, landsberger_allee_rhinstr, 1, 16).
connection(landsberger_allee_rhinstr, schalkauer_str, 2, 16).
connection(schalkauer_str, arendsweg, 1, 16).
connection(arendsweg, genslerstr, 2, 16).
connection(genslerstr, zechliner_str, 1, 16).
connection(zechliner_str, altenhofer_str, 1, 16).
connection(altenhofer_str, hohenschoenhauser_str, 2, 16).
connection(hohenschoenhauser_str, landsberger_allee_weissenseer_w, 2, 16).
connection(landsberger_allee_weissenseer_w, roederplatz, 1, 16).
connection(roederplatz, moellendorffstr_storkower_str, 2, 16).
connection(moellendorffstr_storkower_str, loeperplatz, 2, 16).
connection(loeperplatz, rathaus_lichtenberg, 1, 16).
connection(rathaus_lichtenberg, frankfurter_allee, 2, 16).
connection(frankfurter_allee, jessnerstr, 2, 16).
connection(riesaer_str, riesaer_str_louis_lewin_str, 1, 18).
connection(riesaer_str_louis_lewin_str, jenaer_str, 1, 18).
connection(jenaer_str, nossener_str, 1, 18).
connection(nossener_str, hellersdorf, 1, 18).
connection(hellersdorf, stendaler_str_quedlinburger_str, 2, 18).
connection(stendaler_str_quedlinburger_str, stendaler_str_zossener_str, 1, 18).
connection(stendaler_str_zossener_str, zossener_str_kastanienallee, 1, 18).
connection(zossener_str_kastanienallee, alte_hellersdorfer_zossener_str, 1, 18).
connection(alte_hellersdorfer_zossener_str, michendorfer_str, 1, 18).
connection(michendorfer_str, landsberger_ch_zossener_str, 1, 18).
connection(landsberger_ch_zossener_str, betriebshof_marzahn, 2, 18).
connection(betriebshof_marzahn, brodowiner_ring, 1, 18).
connection(brodowiner_ring, landsberger_allee_blumberger_d, 1, 18).
connection(landsberger_allee_blumberger_d, alt_marzahn, 2, 18).
connection(alt_marzahn, adersleber_weg, 1, 18).
connection(adersleber_weg, allee_d_kosmonauten_poelchaustr, 2, 18).
connection(allee_d_kosmonauten_poelchaustr, boschpoler_str, 2, 18).
connection(boschpoler_str, helene_weigel_platz, 1, 18).
connection(helene_weigel_platz, springpfuhl, 1, 18).
connection(springpfuhl, beilsteiner_str, 1, 18).
connection(beilsteiner_str, allee_der_kosmonauten_rhinstr, 2, 18).
connection(allee_der_kosmonauten_rhinstr, ev_krankenhaus_keh, 2, 18).
connection(ev_krankenhaus_keh, herzbergstr_siegfriedstr, 2, 18).
connection(herzbergstr_siegfriedstr, herzbergstr_industriegebiet, 1, 18).
connection(herzbergstr_industriegebiet, bernhard_baestlein_str, 2, 18).
connection(bernhard_baestlein_str, roederplatz, 1, 18).
connection(roederplatz, anton_saefkow_platz, 1, 18).
connection(anton_saefkow_platz, karl_lade_str, 2, 18).
connection(karl_lade_str, landsberger_allee, 2, 18).
connection(landsberger_allee, landsberger_al_petersburger_str, 2, 18).
connection(landsberger_al_petersburger_str, virchowstr, 1, 18).
connection(pasedagplatz, berliner_allee_rennbahnstr, 1, 27).
connection(berliner_allee_rennbahnstr, buschallee, 3, 27).
connection(buschallee, sulzfelder_str, 1, 27).
connection(sulzfelder_str, hansastr_buschallee, 1, 27).
connection(hansastr_buschallee, orankestrand, 1, 27).
connection(orankestrand, degnerstr_suermondtstr, 2, 27).
connection(degnerstr_suermondtstr, alt_hohenschoenhausen, 2, 27).
connection(alt_hohenschoenhausen, rhinstr_gaertnerstr, 3, 27).
connection(rhinstr_gaertnerstr, rhinstr_plauener_str, 1, 27).
connection(rhinstr_plauener_str, landsberger_allee_rhinstr, 1, 27).
connection(landsberger_allee_rhinstr, meeraner_str, 2, 27).
connection(meeraner_str, allee_der_kosmonauten_rhinstr, 2, 27).
connection(allee_der_kosmonauten_rhinstr, kleingartenanlage_bielefeldt, 1, 27).
connection(kleingartenanlage_bielefeldt, friedrichsfelde_ost, 1, 27).
connection(friedrichsfelde_ost, alt_friedrichsfelde_rhinstr, 2, 27).
connection(alt_friedrichsfelde_rhinstr, alfred_kowalke_str, 2, 27).
connection(alfred_kowalke_str, criegernweg, 1, 27).
connection(criegernweg, tierpark, 1, 27).
connection(tierpark, treskowallee_htw, 2, 27).
connection(treskowallee_htw, marksburgstr, 2, 27).
connection(marksburgstr, karlshorst, 3, 27).
connection(karlshorst, traberweg, 2, 27).
connection(traberweg, hegemeisterweg, 1, 27).
connection(hegemeisterweg, volkspark_wuhlheide, 1, 27).
connection(volkspark_wuhlheide, rummelsburger_str_edisonstr, 1, 27).
connection(rummelsburger_str_edisonstr, wilhelminenhofstr_edisonstr, 2, 27).
connection(wilhelminenhofstr_edisonstr, firlstr, 2, 27).
connection(firlstr, rathenaustr_htw, 1, 27).
connection(rathenaustr_htw, ostendstr, 2, 27).
connection(ostendstr, weiskopffstr, 1, 27).
connection(weiskopffstr, freizeit_und_erholungszentrum, 1, 27).
connection(freizeit_und_erholungszentrum, nixenstr, 1, 27).
connection(nixenstr, spindlersfelder_str, 1, 27).
connection(spindlersfelder_str, alte_foersterei, 1, 27).
connection(alte_foersterei, bahnhofstr_lindenstr, 3, 27).
connection(bahnhofstr_lindenstr, rathaus_koepenick, 2, 27).
connection(rathaus_koepenick, schlossplatz_koepenick, 1, 27).
connection(schlossplatz_koepenick, mueggelhmstr_wendenschlossstr, 2, 27).
connection(mueggelhmstr_wendenschlossstr, pablo_neruda_str, 1, 27).
connection(pablo_neruda_str, krkhs_koepenick_suedseite, 1, 27).
connection(guyotstr, hugenottenplatz, 1, 50).
connection(hugenottenplatz, arnouxstr, 1, 50).
connection(arnouxstr, navarraplatz, 1, 50).
connection(navarraplatz, franzoesisch_buchholz_kirche, 1, 50).
connection(franzoesisch_buchholz_kirche, blankenfelder_str, 1, 50).
connection(blankenfelder_str, rosenthaler_str, 1, 50).
connection(rosenthaler_str, marienstr_pasewalker_str, 1, 50).
connection(marienstr_pasewalker_str, pasewalker_str_blankenburger_weg, 1, 50).
connection(pasewalker_str_blankenburger_weg, pankower_str, 1, 50).
connection(pankower_str, galenusstr, 2, 50).
connection(galenusstr, pankow_heinersdorf, 1, 50).
connection(pankow_heinersdorf, wuertzstr, 1, 50).
connection(wuertzstr, mendelstr, 1, 50).
connection(mendelstr, stiftsweg, 1, 50).
connection(stiftsweg, pankow_kirche, 2, 50).
connection(pankow_kirche, pankow, 2, 50).
connection(pankow, masurenstr, 2, 50).
connection(masurenstr, vinetastr, 1, 50).
connection(vinetastr, schoenhauser_allee_bornholmer_str, 2, 50).
connection(schoenhauser_allee_bornholmer_str, schoenfliesser_str, 2, 50).
connection(schoenfliesser_str, bjoernsonstr, 1, 50).
connection(bjoernsonstr, bornholmer_str, 2, 50).
connection(bornholmer_str, gruentaler_str, 1, 50).
connection(gruentaler_str, osloer_str_prinzenallee, 2, 50).
connection(osloer_str_prinzenallee, drontheimer_str, 1, 50).
connection(drontheimer_str, osloer_str, 2, 50).
connection(osloer_str, louise_schroeder_platz, 1, 50).
connection(louise_schroeder_platz, osram_hoefe, 2, 50).
connection(osram_hoefe, seestr, 2, 50).
connection(seestr, seestr_amrumer_str, 1, 50).
connection(seestr_amrumer_str, virchow_klinikum, 1, 50).
connection(haeckelstr, herweghstr, 1, 60).
connection(herweghstr, sterndamm_koenigsheideweg, 2, 60).
connection(sterndamm_koenigsheideweg, pietschkerstr, 1, 60).
connection(pietschkerstr, schoeneweide_sterndamm, 2, 60).
connection(schoeneweide_sterndamm, schoeneweide, 1, 60).
connection(schoeneweide, brueckenstr, 1, 60).
connection(brueckenstr, wilhelminenhofstr_edisonstr, 2, 60).
connection(wilhelminenhofstr_edisonstr, firlstr, 2, 60).
connection(firlstr, rathenaustr_htw, 1, 60).
connection(rathenaustr_htw, ostendstr, 2, 60).
connection(ostendstr, weiskopffstr, 1, 60).
connection(weiskopffstr, freizeit_und_erholungszentrum, 1, 60).
connection(freizeit_und_erholungszentrum, nixenstr, 1, 60).
connection(nixenstr, spindlersfelder_str, 1, 60).
connection(spindlersfelder_str, alte_foersterei, 1, 60).
connection(alte_foersterei, bahnhofstr_lindenstr, 3, 60).
connection(bahnhofstr_lindenstr, bahnhofstr_seelenbinderstr, 2, 60).
connection(bahnhofstr_seelenbinderstr, gelnitzstr, 2, 60).
connection(gelnitzstr, brandenburgplatz, 1, 60).
connection(brandenburgplatz, bellevuestr, 1, 60).
connection(bellevuestr, hirschgarten, 1, 60).
connection(hirschgarten, westendsiedlung, 2, 60).
connection(westendsiedlung, muehlweg, 1, 60).
connection(muehlweg, ahornallee, 1, 60).
connection(ahornallee, friedrichshagen, 2, 60).
connection(friedrichshagen, drachholzstr, 1, 60).
connection(drachholzstr, marktplatz_friedrichshagen, 1, 60).
connection(marktplatz_friedrichshagen, mueggelseedamm_boelschestr, 1, 60).
connection(mueggelseedamm_boelschestr, josef_nawrocki_str, 1, 60).
connection(josef_nawrocki_str, bruno_wille_str, 1, 60).
connection(bruno_wille_str, altes_wasserwerk, 3, 60).
connection(schoeneweide_sterndamm, nieberstr, 8, 61).
connection(nieberstr, landfliegerstr, 2, 61).
connection(landfliegerstr, benno_koenig_str, 2, 61).
connection(benno_koenig_str, gerhard_sedlmayr_str, 2, 61).
connection(gerhard_sedlmayr_str, landschaftspark_johannisthal, 2, 61).
connection(landschaftspark_johannisthal, karl_ziegler_str, 2, 61).
connection(karl_ziegler_str, magnusstr, 1, 61).
connection(magnusstr, walther_nernst_str, 1, 61).
connection(walther_nernst_str, adlershof, 2, 61).
connection(adlershof, marktplatz_adlershof, 3, 61).
connection(marktplatz_adlershof, wassermannstr, 1, 61).
connection(wassermannstr, ottomar_geschke_str, 1, 61).
connection(ottomar_geschke_str, spindlersfeld, 1, 61).
connection(spindlersfeld, koellnischer_platz, 2, 61).
connection(koellnischer_platz, schlossplatz_koepenick, 2, 61).
connection(schlossplatz_koepenick, freiheit, 3, 61).
connection(freiheit, bahnhofstr_lindenstr, 2, 61).
connection(bahnhofstr_lindenstr, bahnhofstr_seelenbinderstr, 2, 61).
connection(bahnhofstr_seelenbinderstr, gelnitzstr, 2, 61).
connection(gelnitzstr, brandenburgplatz, 1, 61).
connection(brandenburgplatz, bellevuestr, 1, 61).
connection(bellevuestr, hirschgarten, 1, 61).
connection(hirschgarten, wassersportzentrum, 2, 61).
connection(wassersportzentrum, spreestr, 1, 61).
connection(spreestr, mueggelseedamm_boelschestr, 3, 61).
connection(mueggelseedamm_boelschestr, marktplatz_friedrichshagen, 1, 61).
connection(marktplatz_friedrichshagen, drachholzstr, 1, 61).
connection(drachholzstr, friedrichshagen, 1, 61).
connection(friedrichshagen, hartlebenstr, 2, 61).
connection(hartlebenstr, wasserwerk_friedrichshagen, 1, 61).
connection(wasserwerk_friedrichshagen, fuerstenwalder_damm, 1, 61).
connection(fuerstenwalder_damm, fuerstenwalder_d_mueggelseedamm, 1, 61).
connection(fuerstenwalder_d_mueggelseedamm, licht_und_luftbad_mueggelsee, 1, 61).
connection(licht_und_luftbad_mueggelsee, strandbad_mueggelsee, 1, 61).
connection(strandbad_mueggelsee, rahnsdorf_waldschaenke, 2, 61).
connection(wendenschloss, mueggelbergallee, 1, 62).
connection(mueggelbergallee, lienhardweg, 1, 62).
connection(lienhardweg, zur_nachtheide, 1, 62).
connection(zur_nachtheide, dregerhoffstr, 1, 62).
connection(dregerhoffstr, pritstabelstr, 1, 62).
connection(pritstabelstr, segewaldweg, 1, 62).
connection(segewaldweg, mayschweg, 1, 62).
connection(mayschweg, betriebshof_koepenick, 1, 62).
connection(betriebshof_koepenick, mueggelhmstr_wendenschlossstr, 2, 62).
connection(mueggelhmstr_wendenschlossstr, freiheit, 2, 62).
connection(freiheit, bahnhofstr_lindenstr, 2, 62).
connection(bahnhofstr_lindenstr, bahnhofstr_seelenbinderstr, 2, 62).
connection(bahnhofstr_seelenbinderstr, koepenick, 2, 62).
connection(koepenick, mittelheide, 2, 62).
connection(mittelheide, wongrowitzer_steig, 1, 62).
connection(wongrowitzer_steig, unter_den_birken, 1, 62).
connection(unter_den_birken, mahlsdorf_sued, 2, 62).
connection(mahlsdorf_sued, hultschiner_damm_seestr, 1, 62).
connection(hultschiner_damm_seestr, roseggerstr, 1, 62).
connection(roseggerstr, erich_baron_weg, 1, 62).
connection(erich_baron_weg, buetower_str, 1, 62).
connection(buetower_str, bruchsaler_str, 1, 62).
connection(bruchsaler_str, eichenhofweg, 1, 62).
connection(eichenhofweg, ledebourstr, 1, 62).
connection(ledebourstr, rahnsdorfer_str, 2, 62).
connection(rahnsdorfer_str, alt_mahlsdorf, 2, 62).
connection(alt_mahlsdorf, wilhelmsmuehlenweg, 2, 62).
connection(wilhelmsmuehlenweg, mahlsdorf, 1, 62).
connection(schoeneweide_sterndamm, schoeneweide, 1, 67).
connection(schoeneweide, brueckenstr, 1, 67).
connection(brueckenstr, wilhelminenhofstr_edisonstr, 2, 67).
connection(wilhelminenhofstr_edisonstr, firlstr, 2, 67).
connection(firlstr, rathenaustr_htw, 1, 67).
connection(rathenaustr_htw, ostendstr, 2, 67).
connection(ostendstr, weiskopffstr, 1, 67).
connection(weiskopffstr, freizeit_und_erholungszentrum, 1, 67).
connection(freizeit_und_erholungszentrum, nixenstr, 1, 67).
connection(nixenstr, spindlersfelder_str, 1, 67).
connection(spindlersfelder_str, alte_foersterei, 1, 67).
connection(alte_foersterei, bahnhofstr_lindenstr, 3, 67).
connection(bahnhofstr_lindenstr, rathaus_koepenick, 2, 67).
connection(rathaus_koepenick, schlossplatz_koepenick, 1, 67).
connection(schlossplatz_koepenick, mueggelhmstr_wendenschlossstr, 2, 67).
connection(mueggelhmstr_wendenschlossstr, pablo_neruda_str, 1, 67).
connection(pablo_neruda_str, krkhs_koepenick_suedseite, 1, 67).
connection(hirtestr, janitzkystr, 1, 68).
connection(janitzkystr, koepenick, 2, 68).
connection(koepenick, bahnhofstr_seelenbinderstr, 2, 68).
connection(bahnhofstr_seelenbinderstr, bahnhofstr_lindenstr, 2, 68).
connection(bahnhofstr_lindenstr, rathaus_koepenick, 2, 68).
connection(rathaus_koepenick, koellnischer_platz, 3, 68).
connection(koellnischer_platz, glienicker_str, 1, 68).
connection(glienicker_str, vollkropfgraben, 1, 68).
connection(vollkropfgraben, rosenweg, 1, 68).
connection(rosenweg, betonwerk, 1, 68).
connection(betonwerk, friedrich_wolf_str, 1, 68).
connection(friedrich_wolf_str, koenigsseestr, 1, 68).
connection(koenigsseestr, wassersportallee, 2, 68).
connection(wassersportallee, gruenau, 1, 68).
connection(gruenau, regattatribuenen, 2, 68).
connection(regattatribuenen, regattastr_sportpromenade, 1, 68).
connection(regattastr_sportpromenade, strandbad_gruenau, 1, 68).
connection(strandbad_gruenau, bammelecke, 2, 68).
connection(bammelecke, richtershorn, 1, 68).
connection(richtershorn, schappachstr, 1, 68).
connection(schappachstr, luebbenauer_weg, 2, 68).
connection(luebbenauer_weg, adlergestell_vetschauer_allee, 1, 68).
connection(adlergestell_vetschauer_allee, zum_seeblick, 2, 68).
connection(zum_seeblick, alt_schmoeckwitz, 3, 68).
connection(warschauer_str, schlesisches_tor, 2, u1).
connection(schlesisches_tor, goerlitzer_bahnhof, 2, u1).
connection(goerlitzer_bahnhof, kottbusser_tor, 1, u1).
connection(kottbusser_tor, prinzenstr, 2, u1).
connection(prinzenstr, hallesches_tor, 2, u1).
connection(hallesches_tor, moeckernbruecke, 2, u1).
connection(moeckernbruecke, gleisdreieck, 1, u1).
connection(gleisdreieck, kurfuerstenstr, 2, u1).
connection(kurfuerstenstr, nollendorfplatz, 2, u1).
connection(nollendorfplatz, wittenbergplatz, 2, u1).
connection(wittenbergplatz, kurfuerstendamm, 1, u1).
connection(kurfuerstendamm, uhlandstr, 1, u1).
connection(pankow, vinetastr, 1, u2).
connection(vinetastr, schoenhauser_allee, 2, u2).
connection(schoenhauser_allee, eberswalder_str, 2, u2).
connection(eberswalder_str, senefelderplatz, 2, u2).
connection(senefelderplatz, rosa_luxemburg_platz, 2, u2).
connection(rosa_luxemburg_platz, alexanderplatz, 2, u2).
connection(alexanderplatz, klosterstr, 2, u2).
connection(klosterstr, maerkisches_museum, 1, u2).
connection(maerkisches_museum, spittelmarkt, 2, u2).
connection(spittelmarkt, hausvogteiplatz, 2, u2).
connection(hausvogteiplatz, stadtmitte, 2, u2).
connection(stadtmitte, mohrenstr, 1, u2).
connection(mohrenstr, potsdamer_platz, 1, u2).
connection(potsdamer_platz, mendelssohn_bartholdy_park, 2, u2).
connection(mendelssohn_bartholdy_park, gleisdreieck, 1, u2).
connection(gleisdreieck, buelowstr, 2, u2).
connection(buelowstr, nollendorfplatz, 2, u2).
connection(nollendorfplatz, wittenbergplatz, 1, u2).
connection(wittenbergplatz, zoologischer_garten, 3, u2).
connection(zoologischer_garten, ernst_reuter_platz, 1, u2).
connection(ernst_reuter_platz, deutsche_oper, 2, u2).
connection(deutsche_oper, bismarckstr, 1, u2).
connection(bismarckstr, sophie_charlotte_platz, 2, u2).
connection(sophie_charlotte_platz, kaiserdamm, 1, u2).
connection(kaiserdamm, theodor_heuss_platz, 2, u2).
connection(theodor_heuss_platz, neu_westend, 2, u2).
connection(neu_westend, olympia_stadion, 1, u2).
connection(olympia_stadion, ruhleben, 2, u2).
connection(warschauer_str, schlesisches_tor, 2, u3).
connection(schlesisches_tor, goerlitzer_bahnhof, 2, u3).
connection(goerlitzer_bahnhof, kottbusser_tor, 1, u3).
connection(kottbusser_tor, prinzenstr, 2, u3).
connection(prinzenstr, hallesches_tor, 2, u3).
connection(hallesches_tor, moeckernbruecke, 2, u3).
connection(moeckernbruecke, gleisdreieck, 1, u3).
connection(gleisdreieck, kurfuerstenstr, 2, u3).
connection(kurfuerstenstr, nollendorfplatz, 2, u3).
connection(nollendorfplatz, wittenbergplatz, 2, u3).
connection(wittenbergplatz, augsburger_str, 2, u3).
connection(augsburger_str, spichernstr, 1, u3).
connection(spichernstr, hohenzollernplatz, 2, u3).
connection(hohenzollernplatz, fehrbelliner_platz, 1, u3).
connection(fehrbelliner_platz, heidelberger_platz, 2, u3).
connection(heidelberger_platz, ruedesheimer_platz, 2, u3).
connection(ruedesheimer_platz, breitenbachplatz, 1, u3).
connection(breitenbachplatz, podbielskiallee, 2, u3).
connection(podbielskiallee, dahlem_dorf, 1, u3).
connection(dahlem_dorf, freie_universitaet_thielplatz, 2, u3).
connection(freie_universitaet_thielplatz, oskar_helene_heim, 2, u3).
connection(oskar_helene_heim, onkel_toms_huette, 2, u3).
connection(onkel_toms_huette, krumme_lanke, 2, u3).
connection(nollendorfplatz, viktoria_luise_platz, 2, u4).
connection(viktoria_luise_platz, bayerischer_platz, 1, u4).
connection(bayerischer_platz, rathaus_schoeneberg, 2, u4).
connection(rathaus_schoeneberg, innsbrucker_platz, 1, u4).
connection(hoenow, louis_lewin_str, 2, u5).
connection(louis_lewin_str, hellersdorf, 1, u5).
connection(hellersdorf, cottbusser_platz, 2, u5).
connection(cottbusser_platz, kienberg_gaerten_der_welt, 1, u5).
connection(kienberg_gaerten_der_welt, kaulsdorf_nord, 2, u5).
connection(kaulsdorf_nord, wuhletal, 2, u5).
connection(wuhletal, elsterwerdaer_platz, 2, u5).
connection(elsterwerdaer_platz, biesdorf_sued, 2, u5).
connection(biesdorf_sued, tierpark, 3, u5).
connection(tierpark, friedrichsfelde, 2, u5).
connection(friedrichsfelde, lichtenberg, 2, u5).
connection(lichtenberg, magdalenenstr, 1, u5).
connection(magdalenenstr, frankfurter_allee, 2, u5).
connection(frankfurter_allee, samariterstr, 1, u5).
connection(samariterstr, frankfurter_tor, 2, u5).
connection(frankfurter_tor, weberwiese, 1, u5).
connection(weberwiese, strausberger_platz, 1, u5).
connection(strausberger_platz, schillingstr, 2, u5).
connection(schillingstr, alexanderplatz, 2, u5).
connection(alexanderplatz, rotes_rathaus, 1, u5).
connection(rotes_rathaus, museumsinsel, 1, u5).
connection(museumsinsel, unter_den_linden, 2, u5).
connection(unter_den_linden, brandenburger_tor, 1, u5).
connection(brandenburger_tor, bundestag, 1, u5).
connection(bundestag, hauptbahnhof, 2, u5).
connection(alt_tegel, borsigwerke, 1, u6).
connection(borsigwerke, holzhauser_str, 2, u6).
connection(holzhauser_str, otisstr, 1, u6).
connection(otisstr, scharnweberstr, 1, u6).
connection(scharnweberstr, kurt_schumacher_platz, 2, u6).
connection(kurt_schumacher_platz, afrikanische_str, 1, u6).
connection(afrikanische_str, rehberge, 1, u6).
connection(rehberge, seestr, 2, u6).
connection(seestr, leopoldplatz, 2, u6).
connection(leopoldplatz, wedding, 1, u6).
connection(wedding, sellerstr_u_reinickendorfer_str, 1, u6).
connection(sellerstr_u_reinickendorfer_str, schwartzkopffstr, 1, u6).
connection(schwartzkopffstr, naturkundemuseum, 1, u6).
connection(naturkundemuseum, oranienburger_tor, 2, u6).
connection(oranienburger_tor, friedrichstr, 1, u6).
connection(friedrichstr, unter_den_linden, 1, u6).
connection(unter_den_linden, stadtmitte, 2, u6).
connection(stadtmitte, kochstr_checkpoint_charlie, 1, u6).
connection(kochstr_checkpoint_charlie, hallesches_tor, 1, u6).
connection(hallesches_tor, mehringdamm, 2, u6).
connection(mehringdamm, platz_der_luftbruecke, 2, u6).
connection(platz_der_luftbruecke, paradestr, 1, u6).
connection(paradestr, tempelhof, 2, u6).
connection(tempelhof, alt_tempelhof, 1, u6).
connection(alt_tempelhof, kaiserin_augusta_str, 1, u6).
connection(kaiserin_augusta_str, ullsteinstr, 1, u6).
connection(ullsteinstr, westphalweg, 2, u6).
connection(westphalweg, alt_mariendorf, 1, u6).
connection(rathaus_spandau, altstadt_spandau, 1, u7).
connection(altstadt_spandau, zitadelle, 1, u7).
connection(zitadelle, haselhorst, 2, u7).
connection(haselhorst, paulsternstr, 2, u7).
connection(paulsternstr, rohrdamm, 1, u7).
connection(rohrdamm, siemensdamm, 2, u7).
connection(siemensdamm, halemweg, 1, u7).
connection(halemweg, jakob_kaiser_platz, 1, u7).
connection(jakob_kaiser_platz, jungfernheide, 2, u7).
connection(jungfernheide, mierendorffplatz, 1, u7).
connection(mierendorffplatz, richard_wagner_platz, 2, u7).
connection(richard_wagner_platz, bismarckstr, 1, u7).
connection(bismarckstr, wilmersdorfer_str, 1, u7).
connection(wilmersdorfer_str, adenauerplatz, 2, u7).
connection(adenauerplatz, konstanzer_str, 1, u7).
connection(konstanzer_str, fehrbelliner_platz, 1, u7).
connection(fehrbelliner_platz, blissestr, 2, u7).
connection(blissestr, berliner_str, 1, u7).
connection(berliner_str, bayerischer_platz, 1, u7).
connection(bayerischer_platz, eisenacher_str, 1, u7).
connection(eisenacher_str, kleistpark, 2, u7).
connection(kleistpark, yorckstr, 1, u7).
connection(yorckstr, moeckernbruecke, 2, u7).
connection(moeckernbruecke, mehringdamm, 2, u7).
connection(mehringdamm, gneisenaustr, 1, u7).
connection(gneisenaustr, suedstern, 2, u7).
connection(suedstern, hermannplatz, 2, u7).
connection(hermannplatz, rathaus_neukoelln, 1, u7).
connection(rathaus_neukoelln, karl_marx_str, 2, u7).
connection(karl_marx_str, neukoelln, 1, u7).
connection(neukoelln, grenzallee, 2, u7).
connection(grenzallee, blaschkoallee, 1, u7).
connection(blaschkoallee, parchimer_allee, 2, u7).
connection(parchimer_allee, britz_sued, 1, u7).
connection(britz_sued, johannisthaler_chaussee, 2, u7).
connection(johannisthaler_chaussee, lipschitzallee, 1, u7).
connection(lipschitzallee, wutzkyallee, 2, u7).
connection(wutzkyallee, zwickauer_damm, 1, u7).
connection(zwickauer_damm, rudow, 1, u7).
connection(osloer_str, nauener_platz, 1, u9).
connection(nauener_platz, leopoldplatz, 1, u9).
connection(leopoldplatz, amrumer_str, 2, u9).
connection(amrumer_str, westhafen, 1, u9).
connection(westhafen, birkenstr, 1, u9).
connection(birkenstr, turmstr, 2, u9).
connection(turmstr, hansaplatz, 1, u9).
connection(hansaplatz, zoologischer_garten, 2, u9).
connection(zoologischer_garten, kurfuerstendamm, 2, u9).
connection(kurfuerstendamm, spichernstr, 1, u9).
connection(spichernstr, guentzelstr, 1, u9).
connection(guentzelstr, berliner_str, 1, u9).
connection(berliner_str, bundesplatz, 2, u9).
connection(bundesplatz, friedrich_wilhelm_platz, 1, u9).
connection(friedrich_wilhelm_platz, walther_schreiber_platz, 1, u9).
connection(walther_schreiber_platz, schlossstr, 2, u9).
connection(schlossstr, rathaus_steglitz, 1, u9).
connection(wittenau, rathaus_reinickendorf, 1, u8).
connection(rathaus_reinickendorf, karl_bonhoeffer_nervenklinik, 2, u8).
connection(karl_bonhoeffer_nervenklinik, lindauer_allee, 2, u8).
connection(lindauer_allee, paracelsus_bad, 1, u8).
connection(paracelsus_bad, residenzstr, 1, u8).
connection(residenzstr, franz_neumann_platz, 2, u8).
connection(franz_neumann_platz, osloer_str, 2, u8).
connection(osloer_str, pankstr, 1, u8).
connection(pankstr, gesundbrunnen, 2, u8).
connection(gesundbrunnen, voltastr, 1, u8).
connection(voltastr, bernauer_str, 2, u8).
connection(bernauer_str, rosenthaler_platz, 1, u8).
connection(rosenthaler_platz, weinmeisterstr, 2, u8).
connection(weinmeisterstr, alexanderplatz, 2, u8).
connection(alexanderplatz, jannowitzbruecke, 1, u8).
connection(jannowitzbruecke, heinrich_heine_str, 2, u8).
connection(heinrich_heine_str, moritzplatz, 1, u8).
connection(moritzplatz, kottbusser_tor, 2, u8).
connection(kottbusser_tor, schoenleinstr, 2, u8).
connection(schoenleinstr, hermannplatz, 2, u8).
connection(hermannplatz, boddinstr, 1, u8).
connection(boddinstr, leinestr, 2, u8).
connection(leinestr, hermannstr, 1, u8).
connection(heinersdorf, rothenbachstr, 1, m2).
connection(rothenbachstr, heinersdorf_kirche, 1, m2).
connection(heinersdorf_kirche, am_wasserturm, 3, m2).
connection(am_wasserturm, tino_schwierzina_str, 1, m2).
connection(tino_schwierzina_str, am_steinberg, 1, m2).
connection(am_steinberg, prenzlauer_prom_am_steinberg, 1, m2).
connection(prenzlauer_prom_am_steinberg, prenzlauer_allee_ostseestr, 2, m2).
connection(prenzlauer_allee_ostseestr, erich_weinert_str, 1, m2).
connection(erich_weinert_str, prenzlauer_allee, 2, m2).
connection(prenzlauer_allee, froebelstr, 1, m2).
connection(froebelstr, prenzlauer_allee_danziger_str, 2, m2).
connection(prenzlauer_allee_danziger_str, marienburger_str, 2, m2).
connection(marienburger_str, knaackstr, 1, m2).
connection(knaackstr, prenzlauer_allee_metzer_str, 1, m2).
connection(prenzlauer_allee_metzer_str, mollstr_prenzlauer_allee, 1, m2).
connection(mollstr_prenzlauer_allee, alexanderplatz_memhardstr, 2, m2).
connection(alexanderplatz_memhardstr, alexanderplatz_dircksenstr, 2, m2).
connection(falkenberg, welsestr, 1, m4).
connection(welsestr, prendener_str, 1, m4).
connection(prendener_str, hohenschoenhausen, 1, m4).
connection(hohenschoenhausen, prerower_platz, 2, m4).
connection(prerower_platz, hansastr_malchower_weg, 1, m4).
connection(hansastr_malchower_weg, feldtmannstr, 1, m4).
connection(feldtmannstr, stadion_buschallee_hansastr, 1, m4).
connection(stadion_buschallee_hansastr, giersstr, 1, m4).
connection(giersstr, sulzfelder_str, 2, m4).
connection(sulzfelder_str, buschallee, 1, m4).
connection(buschallee, weisser_see, 2, m4).
connection(weisser_see, albertinenstr, 2, m4).
connection(albertinenstr, antonplatz, 1, m4).
connection(antonplatz, greifswalder_str_ostseestr, 2, m4).
connection(greifswalder_str_ostseestr, thomas_mann_str, 1, m4).
connection(thomas_mann_str, greifswalder_str, 1, m4).
connection(greifswalder_str, greifswalder_str_danziger_str, 2, m4).
connection(greifswalder_str_danziger_str, hufelandstr, 2, m4).
connection(hufelandstr, am_friedrichshain, 1, m4).
connection(am_friedrichshain, mollstr_otto_braun_str, 2, m4).
connection(mollstr_otto_braun_str, alexanderplatz, 3, m4).
connection(alexanderplatz, alexanderplatz_gontardstr, 2, m4).
connection(alexanderplatz_gontardstr, spandauer_str_marienkirche, 2, m4).
connection(spandauer_str_marienkirche, hackescher_markt, 1, m4).
connection(riesaer_str, riesaer_str_louis_lewin_str, 1, m6).
connection(riesaer_str_louis_lewin_str, jenaer_str, 1, m6).
connection(jenaer_str, nossener_str, 1, m6).
connection(nossener_str, hellersdorf, 1, m6).
connection(hellersdorf, stendaler_str_quedlinburger_str, 2, m6).
connection(stendaler_str_quedlinburger_str, stendaler_str_zossener_str, 1, m6).
connection(stendaler_str_zossener_str, zossener_str_kastanienallee, 1, m6).
connection(zossener_str_kastanienallee, alte_hellersdorfer_zossener_str, 1, m6).
connection(alte_hellersdorfer_zossener_str, michendorfer_str, 1, m6).
connection(michendorfer_str, landsberger_ch_zossener_str, 1, m6).
connection(landsberger_ch_zossener_str, betriebshof_marzahn, 2, m6).
connection(betriebshof_marzahn, brodowiner_ring, 1, m6).
connection(brodowiner_ring, landsberger_allee_blumberger_d, 1, m6).
connection(landsberger_allee_blumberger_d, jan_petersen_str, 3, m6).
connection(jan_petersen_str, freizeitforum_marzahn, 2, m6).
connection(freizeitforum_marzahn, marzahner_promenade, 2, m6).
connection(marzahner_promenade, marzahn, 1, m6).
connection(marzahn, gewerbepark_georg_knorr, 2, m6).
connection(gewerbepark_georg_knorr, dingelstaedter_str, 1, m6).
connection(dingelstaedter_str, landsberger_allee_rhinstr, 1, m6).
connection(landsberger_allee_rhinstr, schalkauer_str, 2, m6).
connection(schalkauer_str, arendsweg, 1, m6).
connection(arendsweg, genslerstr, 2, m6).
connection(genslerstr, zechliner_str, 1, m6).
connection(zechliner_str, altenhofer_str, 1, m6).
connection(altenhofer_str, hohenschoenhauser_str, 2, m6).
connection(hohenschoenhauser_str, judith_auer_str, 1, m6).
connection(judith_auer_str, oderbruchstr, 2, m6).
connection(oderbruchstr, landsberger_allee, 3, m6).
connection(landsberger_allee, landsberger_al_petersburger_str, 2, m6).
connection(landsberger_al_petersburger_str, klinikum_im_friedrichshain, 2, m6).
connection(klinikum_im_friedrichshain, platz_der_vereinten_nationen, 1, m6).
connection(platz_der_vereinten_nationen, bueschingstr, 1, m6).
connection(bueschingstr, mollstr_otto_braun_str, 2, m6).
connection(mollstr_otto_braun_str, alexanderplatz, 3, m6).
connection(alexanderplatz, alexanderplatz_gontardstr, 2, m6).
connection(alexanderplatz_gontardstr, spandauer_str_marienkirche, 2, m6).
connection(spandauer_str_marienkirche, hackescher_markt, 1, m6).
connection(ahrensfelde_stadtgrenze, barnimplatz, 1, m8).
connection(barnimplatz, niemegker_str, 1, m8).
connection(niemegker_str, wuhletalstr, 2, m8).
connection(wuhletalstr, max_herrmann_str, 1, m8).
connection(max_herrmann_str, buergerpark_marzahn, 1, m8).
connection(buergerpark_marzahn, jan_petersen_str, 2, m8).
connection(jan_petersen_str, alt_marzahn, 2, m8).
connection(alt_marzahn, adersleber_weg, 1, m8).
connection(adersleber_weg, allee_d_kosmonauten_poelchaustr, 2, m8).
connection(allee_d_kosmonauten_poelchaustr, boschpoler_str, 2, m8).
connection(boschpoler_str, helene_weigel_platz, 1, m8).
connection(helene_weigel_platz, springpfuhl, 1, m8).
connection(springpfuhl, beilsteiner_str, 1, m8).
connection(beilsteiner_str, allee_der_kosmonauten_rhinstr, 2, m8).
connection(allee_der_kosmonauten_rhinstr, ev_krankenhaus_keh, 2, m8).
connection(ev_krankenhaus_keh, herzbergstr_siegfriedstr, 2, m8).
connection(herzbergstr_siegfriedstr, herzbergstr_industriegebiet, 1, m8).
connection(herzbergstr_industriegebiet, bernhard_baestlein_str, 2, m8).
connection(bernhard_baestlein_str, roederplatz, 1, m8).
connection(roederplatz, anton_saefkow_platz, 1, m8).
connection(anton_saefkow_platz, karl_lade_str, 2, m8).
connection(karl_lade_str, landsberger_allee, 2, m8).
connection(landsberger_allee, landsberger_al_petersburger_str, 2, m8).
connection(landsberger_al_petersburger_str, klinikum_im_friedrichshain, 2, m8).
connection(klinikum_im_friedrichshain, platz_der_vereinten_nationen, 1, m8).
connection(platz_der_vereinten_nationen, bueschingstr, 1, m8).
connection(bueschingstr, mollstr_otto_braun_str, 2, m8).
connection(mollstr_otto_braun_str, mollstr_prenzlauer_allee, 2, m8).
connection(mollstr_prenzlauer_allee, rosa_luxemburg_platz, 1, m8).
connection(rosa_luxemburg_platz, rosenthaler_platz, 2, m8).
connection(rosenthaler_platz, brunnenstr_invalidenstr, 2, m8).
connection(brunnenstr_invalidenstr, pappelplatz, 1, m8).
connection(pappelplatz, nordbahnhof, 2, m8).
connection(nordbahnhof, naturkundemuseum, 3, m8).
connection(naturkundemuseum, invalidenpark, 2, m8).
connection(invalidenpark, hauptbahnhof, 2, m8).
connection(hauptbahnhof, lesser_ury_weg, 2, m8).
connection(lesser_ury_weg, lueneburger_str, 1, m8).
connection(virchow_klinikum, seestr_amrumer_str, 1, m13).
connection(seestr_amrumer_str, seestr, 2, m13).
connection(seestr, osram_hoefe, 1, m13).
connection(osram_hoefe, louise_schroeder_platz, 2, m13).
connection(louise_schroeder_platz, osloer_str, 1, m13).
connection(osloer_str, drontheimer_str, 2, m13).
connection(drontheimer_str, osloer_str_prinzenallee, 1, m13).
connection(osloer_str_prinzenallee, gruentaler_str, 1, m13).
connection(gruentaler_str, bornholmer_str, 1, m13).
connection(bornholmer_str, bjoernsonstr, 2, m13).
connection(bjoernsonstr, schoenfliesser_str, 1, m13).
connection(schoenfliesser_str, schoenhauser_allee_bornholmer_str, 1, m13).
connection(schoenhauser_allee_bornholmer_str, stahlheimer_str_wisbyer_str, 2, m13).
connection(stahlheimer_str_wisbyer_str, prenzlauer_allee_ostseestr, 1, m13).
connection(prenzlauer_allee_ostseestr, gustav_adolf_str_langhansstr, 2, m13).
connection(gustav_adolf_str_langhansstr, friesickestr, 2, m13).
connection(friesickestr, behaimstr, 1, m13).
connection(behaimstr, antonplatz, 2, m13).
connection(antonplatz, albertinenstr, 1, m13).
connection(albertinenstr, weisser_see, 2, m13).
connection(weisser_see, gounodstr, 1, m13).
connection(gounodstr, betriebshof_indira_gandhi_str, 2, m13).
connection(betriebshof_indira_gandhi_str, sportforum, 1, m13).
connection(sportforum, hohenschoenhauser_str, 2, m13).
connection(hohenschoenhauser_str, landsberger_allee_weissenseer_w, 2, m13).
connection(landsberger_allee_weissenseer_w, roederplatz, 1, m13).
connection(roederplatz, moellendorffstr_storkower_str, 2, m13).
connection(moellendorffstr_storkower_str, loeperplatz, 2, m13).
connection(loeperplatz, rathaus_lichtenberg, 1, m13).
connection(rathaus_lichtenberg, frankfurter_allee, 2, m13).
connection(frankfurter_allee, jessnerstr, 2, m13).
connection(jessnerstr, traveplatz, 1, m13).
connection(traveplatz, holteistr, 1, m13).
connection(holteistr, wuehlischstr_gaertnerstr, 2, m13).
connection(wuehlischstr_gaertnerstr, simplonstr, 1, m13).
connection(simplonstr, kopernikusstr_warschauer_str, 1, m13).
connection(kopernikusstr_warschauer_str, warschauer_str, 2, m13).
connection(wannsee, nikolassee, 3, s1).
connection(nikolassee, schlachtensee, 2, s1).
connection(schlachtensee, mexikoplatz, 2, s1).
connection(mexikoplatz, zehlendorf, 2, s1).
connection(zehlendorf, sundgauer_str, 3, s1).
connection(sundgauer_str, lichterfelde_west, 2, s1).
connection(lichterfelde_west, botanischer_garten, 2, s1).
connection(botanischer_garten, rathaus_steglitz, 2, s1).
connection(rathaus_steglitz, feuerbachstr, 2, s1).
connection(feuerbachstr, friedenau, 3, s1).
connection(friedenau, schoeneberg, 2, s1).
connection(schoeneberg, julius_leber_bruecke, 3, s1).
connection(julius_leber_bruecke, yorckstr_grossgoerschenstr, 2, s1).
connection(yorckstr_grossgoerschenstr, anhalter_bahnhof, 2, s1).
connection(anhalter_bahnhof, potsdamer_platz, 3, s1).
connection(potsdamer_platz, brandenburger_tor, 2, s1).
connection(brandenburger_tor, friedrichstr, 3, s1).
connection(friedrichstr, oranienburger_str, 2, s1).
connection(oranienburger_str, nordbahnhof, 2, s1).
connection(nordbahnhof, humboldthain, 2, s1).
connection(humboldthain, gesundbrunnen, 2, s1).
connection(gesundbrunnen, bornholmer_str, 3, s1).
connection(bornholmer_str, wollankstr, 3, s1).
connection(wollankstr, schoenholz, 2, s1).
connection(schoenholz, wilhelmsruh, 2, s1).
connection(wilhelmsruh, wittenau, 2, s1).
connection(wittenau, waidmannslust, 2, s1).
connection(waidmannslust, hermsdorf, 2, s1).
connection(hermsdorf, frohnau, 2, s1).
connection(frohnau, hohen_neuendorf, 2, s1).
connection(hohen_neuendorf, birkenwerder, 2, s1).
connection(birkenwerder, borgsdorf, 2, s1).
connection(borgsdorf, lehnitz, 3, s1).
connection(lehnitz, oranienburg, 2, s1).
connection(blankenfelde, mahlow, 2, s2).
connection(mahlow, lichtenrade, 2, s2).
connection(lichtenrade, schichauweg, 4, s2).
connection(schichauweg, buckower_chaussee, 2, s2).
connection(buckower_chaussee, marienfelde, 2, s2).
connection(marienfelde, attilastr, 3, s2).
connection(attilastr, priesterweg, 3, s2).
connection(priesterweg, suedkreuz, 2, s2).
connection(suedkreuz, yorckstr, 2, s2).
connection(yorckstr, anhalter_bahnhof, 2, s2).
connection(anhalter_bahnhof, potsdamer_platz, 2, s2).
connection(potsdamer_platz, brandenburger_tor, 2, s2).
connection(brandenburger_tor, friedrichstr, 3, s2).
connection(friedrichstr, oranienburger_str, 3, s2).
connection(oranienburger_str, nordbahnhof, 4, s2).
connection(nordbahnhof, humboldthain, 3, s2).
connection(humboldthain, gesundbrunnen, 3, s2).
connection(gesundbrunnen, bornholmer_str, 2, s2).
connection(bornholmer_str, pankow, 2, s2).
connection(pankow, pankow_heinersdorf, 4, s2).
connection(pankow_heinersdorf, blankenburg, 2, s2).
connection(blankenburg, karow, 3, s2).
connection(karow, buch, 3, s2).
connection(buch, roentgental, 2, s2).
connection(roentgental, zepernick, 2, s2).
connection(zepernick, bernau_friedenstal, 3, s2).
connection(bernau_friedenstal, bernau, 4, s2).
connection(teltow_stadt, lichterfelde_sued, 2, s25).
connection(lichterfelde_sued, osdorfer_str, 2, s25).
connection(osdorfer_str, lichterfelde_ost, 2, s25).
connection(lichterfelde_ost, lankwitz, 2, s25).
connection(lankwitz, suedende, 3, s25).
connection(suedende, priesterweg, 2, s25).
connection(priesterweg, suedkreuz, 2, s25).
connection(suedkreuz, yorckstr, 2, s25).
connection(yorckstr, anhalter_bahnhof, 2, s25).
connection(anhalter_bahnhof, potsdamer_platz, 2, s25).
connection(potsdamer_platz, brandenburger_tor, 3, s25).
connection(brandenburger_tor, friedrichstr, 3, s25).
connection(friedrichstr, oranienburger_str, 2, s25).
connection(oranienburger_str, nordbahnhof, 3, s25).
connection(nordbahnhof, humboldthain, 2, s25).
connection(humboldthain, gesundbrunnen, 3, s25).
connection(gesundbrunnen, bornholmer_str, 2, s25).
connection(bornholmer_str, wollankstr, 2, s25).
connection(wollankstr, schoenholz, 4, s25).
connection(schoenholz, alt_reinickendorf, 2, s25).
connection(alt_reinickendorf, karl_bonhoeffer_nervenklinik, 2, s25).
connection(karl_bonhoeffer_nervenklinik, eichborndamm, 2, s25).
connection(eichborndamm, tegel, 2, s25).
connection(tegel, schulzendorf, 2, s25).
connection(schulzendorf, heiligensee, 3, s25).
connection(heiligensee, hennigsdorf, 2, s25).
connection(teltow_stadt, lichterfelde_sued, 3, s26).
connection(lichterfelde_sued, osdorfer_str, 3, s26).
connection(osdorfer_str, lichterfelde_ost, 4, s26).
connection(lichterfelde_ost, lankwitz, 3, s26).
connection(lankwitz, suedende, 4, s26).
connection(suedende, priesterweg, 3, s26).
connection(priesterweg, suedkreuz, 2, s26).
connection(suedkreuz, yorckstr, 3, s26).
connection(yorckstr, anhalter_bahnhof, 4, s26).
connection(anhalter_bahnhof, potsdamer_platz, 3, s26).
connection(potsdamer_platz, brandenburger_tor, 2, s26).
connection(brandenburger_tor, friedrichstr, 4, s26).
connection(friedrichstr, oranienburger_str, 2, s26).
connection(oranienburger_str, nordbahnhof, 3, s26).
connection(nordbahnhof, humboldthain, 3, s26).
connection(humboldthain, gesundbrunnen, 3, s26).
connection(gesundbrunnen, bornholmer_str, 6, s26).
connection(bornholmer_str, pankow, 2, s26).
connection(pankow, pankow_heinersdorf, 3, s26).
connection(pankow_heinersdorf, blankenburg, 4, s26).
connection(erkner, wilhelmshagen, 2, s3).
connection(wilhelmshagen, rahnsdorf, 3, s3).
connection(rahnsdorf, friedrichshagen, 2, s3).
connection(friedrichshagen, hirschgarten, 2, s3).
connection(hirschgarten, koepenick, 2, s3).
connection(koepenick, wuhlheide, 3, s3).
connection(wuhlheide, karlshorst, 2, s3).
connection(karlshorst, betriebsbahnhof_rummelsburg, 2, s3).
connection(betriebsbahnhof_rummelsburg, rummelsburg, 2, s3).
connection(rummelsburg, ostkreuz, 2, s3).
connection(ostkreuz, warschauer_str, 3, s3).
connection(warschauer_str, ostbahnhof, 3, s3).
connection(ostbahnhof, jannowitzbruecke, 2, s3).
connection(jannowitzbruecke, alexanderplatz, 2, s3).
connection(alexanderplatz, hackescher_markt, 2, s3).
connection(hackescher_markt, friedrichstr, 4, s3).
connection(friedrichstr, hauptbahnhof, 2, s3).
connection(hauptbahnhof, bellevue, 2, s3).
connection(bellevue, tiergarten, 3, s3).
connection(tiergarten, zoologischer_garten, 3, s3).
connection(zoologischer_garten, savignyplatz, 2, s3).
connection(savignyplatz, charlottenburg, 3, s3).
connection(charlottenburg, westkreuz, 2, s3).
connection(westkreuz, messe_sued_eichkamp, 2, s3).
connection(messe_sued_eichkamp, heerstr, 2, s3).
connection(heerstr, olympiastadion, 3, s3).
connection(olympiastadion, pichelsberg, 3, s3).
connection(pichelsberg, stresow, 3, s3).
connection(stresow, spandau, 2, s3).
connection(gesundbrunnen, schoenhauser_allee, 2, s41).
connection(schoenhauser_allee, prenzlauer_allee, 2, s41).
connection(prenzlauer_allee, greifswalder_str, 2, s41).
connection(greifswalder_str, landsberger_allee, 2, s41).
connection(landsberger_allee, storkower_str, 2, s41).
connection(storkower_str, frankfurter_allee, 2, s41).
connection(frankfurter_allee, ostkreuz, 2, s41).
connection(ostkreuz, treptower_park, 2, s41).
connection(treptower_park, sonnenallee, 2, s41).
connection(sonnenallee, neukoelln, 2, s41).
connection(neukoelln, hermannstr, 2, s41).
connection(hermannstr, tempelhof, 2, s41).
connection(tempelhof, suedkreuz, 3, s41).
connection(suedkreuz, schoeneberg, 2, s41).
connection(schoeneberg, innsbrucker_platz, 2, s41).
connection(innsbrucker_platz, bundesplatz, 3, s41).
connection(bundesplatz, heidelberger_platz, 2, s41).
connection(heidelberger_platz, hohenzollerndamm, 2, s41).
connection(hohenzollerndamm, halensee, 2, s41).
connection(halensee, westkreuz, 2, s41).
connection(westkreuz, messe_nord_icc_witzleben, 2, s41).
connection(messe_nord_icc_witzleben, westend, 2, s41).
connection(westend, jungfernheide, 2, s41).
connection(jungfernheide, beusselstr, 2, s41).
connection(beusselstr, westhafen, 3, s41).
connection(westhafen, wedding, 2, s41).
connection(wedding, gesundbrunnen, 2, s41).
connection(gesundbrunnen, wedding, 2, s42).
connection(wedding, westhafen, 2, s42).
connection(westhafen, beusselstr, 2, s42).
connection(beusselstr, jungfernheide, 2, s42).
connection(jungfernheide, westend, 3, s42).
connection(westend, messe_nord_icc_witzleben, 2, s42).
connection(messe_nord_icc_witzleben, westkreuz, 2, s42).
connection(westkreuz, halensee, 2, s42).
connection(halensee, hohenzollerndamm, 2, s42).
connection(hohenzollerndamm, heidelberger_platz, 2, s42).
connection(heidelberger_platz, bundesplatz, 2, s42).
connection(bundesplatz, innsbrucker_platz, 2, s42).
connection(innsbrucker_platz, schoeneberg, 2, s42).
connection(schoeneberg, suedkreuz, 3, s42).
connection(suedkreuz, tempelhof, 2, s42).
connection(tempelhof, hermannstr, 2, s42).
connection(hermannstr, neukoelln, 2, s42).
connection(neukoelln, sonnenallee, 2, s42).
connection(sonnenallee, treptower_park, 2, s42).
connection(treptower_park, ostkreuz, 2, s42).
connection(ostkreuz, frankfurter_allee, 2, s42).
connection(frankfurter_allee, storkower_str, 2, s42).
connection(storkower_str, landsberger_allee, 2, s42).
connection(landsberger_allee, greifswalder_str, 2, s42).
connection(greifswalder_str, prenzlauer_allee, 2, s42).
connection(prenzlauer_allee, schoenhauser_allee, 2, s42).
connection(schoenhauser_allee, gesundbrunnen, 2, s42).
connection(flughafen_ber, wassmannsdorf, 3, s45).
connection(wassmannsdorf, schoenefeld_bei_berlin, 2, s45).
connection(schoenefeld_bei_berlin, gruenbergallee, 2, s45).
connection(gruenbergallee, altglienicke, 3, s45).
connection(altglienicke, adlershof, 3, s45).
connection(adlershof, johannisthal, 2, s45).
connection(johannisthal, schoeneweide, 2, s45).
connection(schoeneweide, baumschulenweg, 2, s45).
connection(baumschulenweg, koellnische_heide, 2, s45).
connection(koellnische_heide, neukoelln, 2, s45).
connection(neukoelln, hermannstr, 4, s45).
connection(hermannstr, tempelhof, 2, s45).
connection(tempelhof, suedkreuz, 2, s45).
connection(koenigs_wusterhausen, wildau, 4, s46).
connection(wildau, zeuthen, 2, s46).
connection(zeuthen, eichwalde, 3, s46).
connection(eichwalde, gruenau, 2, s46).
connection(gruenau, adlershof, 5, s46).
connection(adlershof, johannisthal, 3, s46).
connection(johannisthal, schoeneweide, 4, s46).
connection(schoeneweide, baumschulenweg, 6, s46).
connection(baumschulenweg, koellnische_heide, 2, s46).
connection(koellnische_heide, neukoelln, 3, s46).
connection(neukoelln, hermannstr, 2, s46).
connection(hermannstr, tempelhof, 3, s46).
connection(tempelhof, suedkreuz, 3, s46).
connection(suedkreuz, schoeneberg, 3, s46).
connection(schoeneberg, innsbrucker_platz, 2, s46).
connection(innsbrucker_platz, bundesplatz, 3, s46).
connection(bundesplatz, heidelberger_platz, 4, s46).
connection(heidelberger_platz, hohenzollerndamm, 2, s46).
connection(hohenzollerndamm, halensee, 5, s46).
connection(halensee, westkreuz, 3, s46).
connection(westkreuz, messe_nord_icc_witzleben, 3, s46).
connection(messe_nord_icc_witzleben, westend, 2, s46).
connection(spindlersfeld, oberspree, 2, s47).
connection(oberspree, schoeneweide, 3, s47).
connection(schoeneweide, baumschulenweg, 3, s47).
connection(baumschulenweg, koellnische_heide, 3, s47).
connection(koellnische_heide, neukoelln, 3, s47).
connection(neukoelln, hermannstr, 2, s47).
connection(strausberg_nord, strausberg_stadt, 3, s5).
connection(strausberg_stadt, hegermuehle, 3, s5).
connection(hegermuehle, strausberg, 3, s5).
connection(strausberg, petershagen_nord, 2, s5).
connection(petershagen_nord, fredersdorf, 2, s5).
connection(fredersdorf, neuenhagen, 2, s5).
connection(neuenhagen, hoppegarten_mark, 2, s5).
connection(hoppegarten_mark, birkenstein, 3, s5).
connection(birkenstein, mahlsdorf, 2, s5).
connection(mahlsdorf, kaulsdorf, 2, s5).
connection(kaulsdorf, wuhletal, 3, s5).
connection(wuhletal, biesdorf, 2, s5).
connection(biesdorf, friedrichsfelde_ost, 2, s5).
connection(friedrichsfelde_ost, lichtenberg, 4, s5).
connection(lichtenberg, noeldnerplatz, 2, s5).
connection(noeldnerplatz, ostkreuz, 4, s5).
connection(ostkreuz, warschauer_str, 2, s5).
connection(warschauer_str, ostbahnhof, 2, s5).
connection(ostbahnhof, jannowitzbruecke, 3, s5).
connection(jannowitzbruecke, alexanderplatz, 3, s5).
connection(alexanderplatz, hackescher_markt, 2, s5).
connection(hackescher_markt, friedrichstr, 2, s5).
connection(friedrichstr, hauptbahnhof, 2, s5).
connection(hauptbahnhof, bellevue, 3, s5).
connection(bellevue, tiergarten, 2, s5).
connection(tiergarten, zoologischer_garten, 4, s5).
connection(zoologischer_garten, savignyplatz, 3, s5).
connection(savignyplatz, charlottenburg, 2, s5).
connection(charlottenburg, westkreuz, 3, s5).
connection(ahrensfelde, mehrower_allee, 2, s7).
connection(mehrower_allee, raoul_wallenberg_str, 2, s7).
connection(raoul_wallenberg_str, marzahn, 3, s7).
connection(marzahn, poelchaustr, 2, s7).
connection(poelchaustr, springpfuhl, 2, s7).
connection(springpfuhl, friedrichsfelde_ost, 2, s7).
connection(friedrichsfelde_ost, lichtenberg, 2, s7).
connection(lichtenberg, noeldnerplatz, 3, s7).
connection(noeldnerplatz, ostkreuz, 2, s7).
connection(ostkreuz, warschauer_str, 3, s7).
connection(warschauer_str, ostbahnhof, 2, s7).
connection(ostbahnhof, jannowitzbruecke, 2, s7).
connection(jannowitzbruecke, alexanderplatz, 2, s7).
connection(alexanderplatz, hackescher_markt, 2, s7).
connection(hackescher_markt, friedrichstr, 3, s7).
connection(friedrichstr, hauptbahnhof, 2, s7).
connection(hauptbahnhof, bellevue, 2, s7).
connection(bellevue, tiergarten, 3, s7).
connection(tiergarten, zoologischer_garten, 4, s7).
connection(zoologischer_garten, savignyplatz, 2, s7).
connection(savignyplatz, charlottenburg, 3, s7).
connection(charlottenburg, westkreuz, 3, s7).
connection(westkreuz, grunewald, 3, s7).
connection(grunewald, nikolassee, 2, s7).
connection(nikolassee, wannsee, 2, s7).
connection(wannsee, griebnitzsee, 2, s7).
connection(griebnitzsee, babelsberg, 3, s7).
connection(babelsberg, potsdam_hbf, 3, s7).
connection(wartenberg, hohenschoenhausen, 2, s75).
connection(hohenschoenhausen, gehrenseestr, 3, s75).
connection(gehrenseestr, springpfuhl, 2, s75).
connection(springpfuhl, friedrichsfelde_ost, 3, s75).
connection(friedrichsfelde_ost, lichtenberg, 2, s75).
connection(lichtenberg, noeldnerplatz, 2, s75).
connection(noeldnerplatz, ostkreuz, 2, s75).
connection(ostkreuz, warschauer_str, 3, s75).
connection(wildau, zeuthen, 4, s8).
connection(zeuthen, eichwalde, 3, s8).
connection(eichwalde, gruenau, 4, s8).
connection(gruenau, adlershof, 2, s8).
connection(adlershof, johannisthal, 4, s8).
connection(johannisthal, schoeneweide, 3, s8).
connection(schoeneweide, baumschulenweg, 3, s8).
connection(baumschulenweg, plaenterwald, 2, s8).
connection(plaenterwald, treptower_park, 3, s8).
connection(treptower_park, ostkreuz, 2, s8).
connection(ostkreuz, frankfurter_allee, 2, s8).
connection(frankfurter_allee, storkower_str, 4, s8).
connection(storkower_str, landsberger_allee, 2, s8).
connection(landsberger_allee, greifswalder_str, 2, s8).
connection(greifswalder_str, prenzlauer_allee, 3, s8).
connection(prenzlauer_allee, schoenhauser_allee, 3, s8).
connection(schoenhauser_allee, bornholmer_str, 2, s8).
connection(bornholmer_str, pankow, 2, s8).
connection(pankow, pankow_heinersdorf, 5, s8).
connection(pankow_heinersdorf, blankenburg, 2, s8).
connection(blankenburg, muehlenbeck_moenchmuehle, 3, s8).
connection(muehlenbeck_moenchmuehle, schoenfliess, 3, s8).
connection(schoenfliess, bergfelde, 3, s8).
connection(bergfelde, hohen_neuendorf, 6, s8).
connection(hohen_neuendorf, birkenwerder, 4, s8).
connection(gruenau, adlershof, 3, s85).
connection(adlershof, johannisthal, 3, s85).
connection(johannisthal, schoeneweide, 2, s85).
connection(schoeneweide, baumschulenweg, 2, s85).
connection(baumschulenweg, plaenterwald, 2, s85).
connection(plaenterwald, treptower_park, 2, s85).
connection(treptower_park, ostkreuz, 3, s85).
connection(ostkreuz, frankfurter_allee, 2, s85).
connection(frankfurter_allee, storkower_str, 2, s85).
connection(storkower_str, landsberger_allee, 2, s85).
connection(landsberger_allee, greifswalder_str, 4, s85).
connection(greifswalder_str, prenzlauer_allee, 2, s85).
connection(prenzlauer_allee, schoenhauser_allee, 2, s85).
connection(schoenhauser_allee, bornholmer_str, 2, s85).
connection(bornholmer_str, wollankstr, 2, s85).
connection(wollankstr, schoenholz, 2, s85).
connection(schoenholz, wilhelmsruh, 2, s85).
connection(wilhelmsruh, wittenau, 2, s85).
connection(wittenau, waidmannslust, 2, s85).
connection(flughafen_ber, wassmannsdorf, 2, s9).
connection(wassmannsdorf, schoenefeld_bei_berlin, 4, s9).
connection(schoenefeld_bei_berlin, gruenbergallee, 2, s9).
connection(gruenbergallee, altglienicke, 2, s9).
connection(altglienicke, adlershof, 2, s9).
connection(adlershof, johannisthal, 2, s9).
connection(johannisthal, schoeneweide, 3, s9).
connection(schoeneweide, baumschulenweg, 3, s9).
connection(baumschulenweg, plaenterwald, 3, s9).
connection(plaenterwald, treptower_park, 4, s9).
connection(treptower_park, warschauer_str, 2, s9).
connection(warschauer_str, ostbahnhof, 2, s9).
connection(ostbahnhof, jannowitzbruecke, 3, s9).
connection(jannowitzbruecke, alexanderplatz, 3, s9).
connection(alexanderplatz, hackescher_markt, 2, s9).
connection(hackescher_markt, friedrichstr, 2, s9).
connection(friedrichstr, hauptbahnhof, 2, s9).
connection(hauptbahnhof, bellevue, 2, s9).
connection(bellevue, tiergarten, 2, s9).
connection(tiergarten, zoologischer_garten, 3, s9).
connection(zoologischer_garten, savignyplatz, 2, s9).
connection(savignyplatz, charlottenburg, 2, s9).
connection(charlottenburg, westkreuz, 3, s9).
connection(westkreuz, messe_sued_eichkamp, 2, s9).
connection(messe_sued_eichkamp, heerstr, 4, s9).
connection(heerstr, olympiastadion, 2, s9).
connection(olympiastadion, pichelsberg, 2, s9).
connection(pichelsberg, stresow, 2, s9).
connection(stresow, spandau, 2, s9).